version: '3.8'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: akcontainer_php
    restart: always
    working_dir: /var/www/
    volumes:
      - ../web:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: akcontainer_web
    restart: always
    ports:
      - 8000:80 # http://localhost:8000/
    volumes:
      - ../web:/var/www
      - ./etc/nginx:/etc/nginx/conf.d
  pma:
        image: phpmyadmin/phpmyadmin
        container_name: akcontainer_phpmyadmin
        ports:
            - "8080:80" # http://localhost:8080/
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysqld
        restart: always
        depends_on:
            - mysqldb
  mysqldb:
        image: mysql:latest
        container_name: akcontainer_mysql
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
